print('PRIMEIRA E ÚLTIMA OCORRÊNCIA DE UMA STRING')
print('>-'*20)
frase = str(input('Digite uma frase: ')).strip().upper()
print(f'\nA letra A aparece {frase.count("A")} vezes na frase')
print(f'A primeira letra A apareceu na posição {frase.find("A")+1}')
print(f'A última letra A apareceu na posição {frase.rfind("A")+1}')
print('>-'*20)
